version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    restart: unless-stopped

  product-service:
    build: ./product-service
    ports:
      - "4000:4000"
    restart: unless-stopped
