apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==  # base64 of "mysecretpassword"
  API_KEY: YXBpa2V5MTIzNDU2                # base64 of "apikey123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
data:
  DB_PASSWORD: cHJvZHVjdHNlY3JldA==       # base64 of "productsecret"
  API_TOKEN: dG9rZW5zZWNyZXQ=             # base64 of "tokensecret"
