apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==  # base64 of "mysecretpassword"
  API_KEY: YXBpa2V5MTIzNDU2                # base64 of "apikey123456"

apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
data:
  DB_PASSWORD: cHJvZHVjdHNlY3JldA==       # base64 of "productsecret"
  API_TOKEN: dG9rZW5zZWNyZXQ=             # base64 of "tokensecret"

  apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
type: Opaque
data:
  NOTIFICATION_API_KEY: eW91cl9kaW15X2FwaV9rZXk=            # base64 of "your_dummy_api_key"
  NOTIFICATION_EMAIL_PASSWORD: eW91cl9kaW15X3Bhc3N3b3Jk     # base64 of "your_dummy_password"

