name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}    # Set this secret in your repo
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push User Service image
      uses: docker/build-push-action@v4
      with:
        context: ./user-service
        push: true
        tags: yourdockerhubusername/user-service:latest

    - name: Build and push Product Service image
      uses: docker/build-push-action@v4
      with:
        context: ./product-service
        push: true
        tags: yourdockerhubusername/product-service:latest

    - name: Run User Service tests
      run: |
        cd user-service
        npm install
        npm test

    - name: Run Product Service tests
      run: |
        cd product-service
        npm install
        npm test

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes cluster
      run: |
        kubectl apply -f k8s/configmaps.yaml
        kubectl apply -f k8s/secrets.yaml
        kubectl apply -f k8s/user-service-deployment.yaml
        kubectl apply -f k8s/product-service-deployment.yaml
        kubectl rollout status deployment/user-service
        kubectl rollout status deployment/product-service
